In [52]:
import numpy as np

In [53]:
mat1D = np.array([1,2,3,4,5,6,7,8,9])
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2D10 = mat2D * 10

In [54]:
print(f"Matriks 1D :\n{mat1D}")
print(f"Matriks 1D indeks ke 7:{mat1D[7]}")
print(f"Matriks 1D * 10 : {mat1D *10}")

Matriks 1D :
[1 2 3 4 5 6 7 8 9]
Matriks 1D indeks ke 7:8
Matriks 1D * 10 : [10 20 30 40 50 60 70 80 90]


In [55]:
print(f"Matriks 2D:\n{mat2D}")
print(f"Matriks 2D * 10 :\n{mat2D * 10}")
print(mat2D10[0])
print(mat2D10[0][2])

Matriks 2D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks 2D * 10 :
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[10 20 30]
30


In [56]:
print(mat1D.shape)
print(mat2D.shape)

(9,)
(3, 3)


In [57]:
print(f"Ukuran dari mat1D:{mat1D.size}")
print(f"Ukuran dari mat2D:{mat2D.size}")

Ukuran dari mat1D:9
Ukuran dari mat2D:9


In [58]:
#spesial matrix
mZero =  np.zeros ((3,3))
mOne = np.ones ((3000,3000))
mFull = np.full((4,4),7) #membuat array ukuran 4*4 diisi dengan nilai 7
mIdentity = np.eye((4))
mFRandom1D = np.random.rand(5)
mFRandom2D = np.random.rand(3,3)
mFRandom1D = np.random.randint(10,100,size=5)
mFRandom1D = np.random.randint(10,100,size=(4,4))
print(f"matriks mZero :n\{mZero}")
print(f"matriks mOne :n\{mOne}")
print(f"matriks mFull :n\{mFull}")
print(f"matriks mIdentity :n\{mIdentity}")
print(f"matriks mFRandom1D :n\{mFRandom1D}")
print(f"matriks mFRandom2D :n\{mFRandom2D}")
print(f"matriks mFRandom1D :n\{mFRandom1D}")
print(f"matriks mFRandom2D :n\{mFRandom2D}")




matriks mZero :n\[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
matriks mOne :n\[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
matriks mFull :n\[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
matriks mIdentity :n\[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
matriks mFRandom1D :n\[[12 59 43 41]
 [11 35 58 54]
 [15 63 62 56]
 [32 31 98 74]]
matriks mFRandom2D :n\[[0.35102668 0.25066615 0.65403457]
 [0.6411511  0.94835898 0.49440741]
 [0.41455776 0.6497039  0.75393755]]
matriks mFRandom1D :n\[[12 59 43 41]
 [11 35 58 54]
 [15 63 62 56]
 [32 31 98 74]]
matriks mFRandom2D :n\[[0.35102668 0.25066615 0.65403457]
 [0.6411511  0.94835898 0.49440741]
 [0.41455776 0.6497039  0.75393755]]


In [59]:
# Mengubah bentuk array
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
mshape = data.reshape((9,1))
mFlat = data.flatten()

print(F"Matriks Data:\n{data}")
print(F"Matriks Reshape:\n{mshape}")
print(F"Matriks mFlat:\n{mFlat}")


Matriks Data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks Reshape:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Matriks mFlat:
[1 2 3 4 5 6 7 8 9]


In [60]:
#Deskriptif Statistik
x = np.array([1,2,3,4])
y = np.array([2,5,7,9])

#Menghitung dot product
r1 = np.dot(x,y)
r2 = np.add(x,y)
print(f"Hasil dari dot product:{r1}")
print(f"Hasil penjumlahan matriks:\n{r2}")
print(f"Nilai minimum : {y.min()}")
print(f"Nilai Maksimum:{y.max()}")
print(f"Nilai Rata-Rata:{y.mean()}")
print(f"Nilai Total:{y.sum()}")
print(f"Nilai Deviasi:{y.std()}")

Hasil dari dot product:69
Hasil penjumlahan matriks:
[ 3  7 10 13]
Nilai minimum : 2
Nilai Maksimum:9
Nilai Rata-Rata:5.75
Nilai Total:23
Nilai Deviasi:2.5860201081971503


In [61]:
#Filtering

nilaiPemrograman = np.array([100,90,100,80,50,50,50,40])
#Tampilkan nilai pemrograman yang lebih dari 50 -> lulus
#berapakah jumlah mahasiswa yang lulus
jmlLuLus = nilaiPemrograman[nilaiPemrograman > 50]
print(jmlLuLus)
print(f"Mahasiswa yang lulus sebanyak :{jmlLuLus.size}")
print(f"Mahasiswa yang tidak lulus : {nilaiPemrograman.size-jmlLuLus.size}")

[100  90 100  80]
Mahasiswa yang lulus sebanyak :4
Mahasiswa yang tidak lulus : 4


<b> Project Generate Data</b> <br>
Buatlah 1000 Data Customer CC, yang akan di gunakan untuk prediksi atau 
klasifikasi yaitu:
</ol>
    <li>usia : 17-60 </li>
    <li> Gender : l/P</li>
    <li>Transaksi perbulan : 0-50</li>
</ol>

In [68]:
import numpy as np 
import pandas as pd

jmlData = 1000
usia = np.random. randint(17,61,size=jmlData)
gender = np.random.choice(['L','P'],size=jmlData)
transaksi = np. random. randint (0,51,size=jmlData)
pembayaran = np.random.choice(['Buruk','Sedang','Bagus'],size=jmlData)

df = pd.DataFrame({
    'usia' : usia,
    'gender': gender,
    'transaksi' : transaksi,
    'pembayaran' : pembayaran
})

print(df)
print(df.info()) #Menampilkan karakteristik data
print(df.head()) #Menampilkan isi tabel 5 baris pertama
#tampilkan usia yang paling muda
print(f"Usia Customer termuda:{df['usia'].min()}")
print(f"Usia Customer tertua:{df['usia'].max()}")
#Tampilkan jumlah customer yang Laki-laki
jmlL = df[df['gender']=='L']
print ("bumlah Customer Laki-laki: {jmlL.size}")
df. to_csv("dataCustomer.csv")

     usia gender  transaksi pembayaran
0      42      L         43     Sedang
1      17      L         12      Bagus
2      51      L          4     Sedang
3      37      L         43     Sedang
4      52      L          8     Sedang
..    ...    ...        ...        ...
995    59      L         13      Bagus
996    35      P         38      Bagus
997    58      L          9      Bagus
998    58      P         24      Bagus
999    44      L          8     Sedang

[1000 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   usia        1000 non-null   int32 
 1   gender      1000 non-null   object
 2   transaksi   1000 non-null   int32 
 3   pembayaran  1000 non-null   object
dtypes: int32(2), object(2)
memory usage: 23.6+ KB
None
   usia gender  transaksi pembayaran
0    42      L         43     Sedang
1    17      L         12      B